# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    pass

def build(bld):
    nr_lib = 'ns3.35-nr-' + bld.env['LIB_SUFFIX']
    flow_monitor_lib = 'ns3.35-flow-monitor-' + bld.env['LIB_SUFFIX']
    # 用 DCE 的封装来构建脚本
    bld.build_a_script(
        'dce',                                  # backend：用 dce
        needed = [
            'core',
            'network',
            'internet',
            'internet-apps',
            'point-to-point',
            'mobility',
            'applications',
            'dce',
            'lte'
        ],
        target = 'bin/nr-dce',           # 生成的可执行文件名
        source = ['nr-dce.cc'],          # 源文件
        lib=[
            nr_lib, flow_monitor_lib]
    )
