# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    pass

def build(bld):
    # 用 DCE 的封装来构建脚本
    bld.build_a_script(
        'dce',                                  # backend：用 dce
        needed = [
            'core',
            'network',
            'internet',
            'point-to-point',
            'mobility',
            'applications',
            'dce',
            'lte',
            'wifi'
        ],
        target = 'bin/app-test1',           # 生成的可执行文件名
        source = ['app-test1.cc', 'rate-dual-helper.cc', 'rate-dual-application.cc'],          # 源文件
        lib=['ns3.35-flow-monitor-debug']
    )
