# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf


def configure(conf):
    pass


def build(bld):
    nr_lib = 'ns3.35-nr-' + bld.env['LIB_SUFFIX']
    bld.build_a_script(
        'dce',
        needed=[
            'core',
            'network',
            'internet',
            'internet-apps',
            'point-to-point',
            'csma',
            'mobility',
            'applications',
            'dce',
            'lte',
            'wifi',
            'spectrum',
        ],
        target='bin/120-demo',
        source=[
            '120-demo.cc',
            '../app-test/rate-dual-helper.cc',
            '../app-test/rate-dual-application.cc',
        ],
        lib=[nr_lib],
    )
    bld.build_a_script(
        'dce',
        needed=[
            'core',
            'network',
            'internet',
            'point-to-point',
            'csma',
            'mobility',
            'applications',
            'wifi',
            'spectrum',
        ],
        target='bin/link-info-wifi-only',
        source=[
            'link-info/wifi-only/link-info-wifi-only.cc',
        ],
    )
    bld.build_a_script(
        'dce',
        needed=[
            'core',
            'network',
            'internet',
            'internet-apps',
            'point-to-point',
            'mobility',
            'applications',
            'flow-monitor',
            'lte',
        ],
        target='bin/link-info-nr-only',
        source=[
            'link-info/nr-only/link-info-nr-only.cc',
        ],
        lib=[nr_lib],
    )
